name: Daily Commit

on:
  schedule:
    - cron: '30 18 * * *'  # Runs daily at 18:30 UTC (Adjust as needed)
  workflow_dispatch:  # Allows manual trigger

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Git Config (23f1002424@ds.study.iitm.ac.in)  # Email added in step name
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "23f1002424@ds.study.iitm.ac.in"

      - name: Make a Change (23f1002424@ds.study.iitm.ac.in)  # Email added in step name
        run: |
          echo "Last run: $(date)" > last_run.txt
          git add last_run.txt


      - name: Commit and Push (23f1002424@ds.study.iitm.ac.in)
        env:
          PAT: ${{ secrets.GH_PAT }}
        run: |
          git commit -m "Automated daily commit at $(date)" || echo "No changes to commit"
          git push https://$PAT@github.com/Adityism/daily-commit-bot.git main
