name: Daily Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "23f1002424@ds.study.iitm.ac.in"

      - name: Make a Change
        run: |
          echo "Last run: $(date)" > last_run.txt  # Always modify the file

      - name: Commit and Push Changes
        run: |
          git add last_run.txt
          git commit -m "Automated daily commit at $(date)" || echo "No changes to commit"
          git push
